### PR TITLE
no hack laserSwitch

### PR DESCRIPTION
**Pull request by jackdunger**
**DON'T MERGE!**
- possible edit to remove the hacked u12 file from LabJackPython, just here for @cjones2500 to look at
- just use the original source code from LabJackPython
- now explicitly call `writeD = 1`, as the default argument isn't the one we want
- the return value of `eDigitalOut(...)` is seemingly not used so don't worry about that
- add the LabJackSubmodule to the python path to avoid having to install just this file

@cjones2500, what do you recon? I know I might be missing something, so feel free to tear this down

### CODE REVIEW

**Comment by jlidgard** [comment]
and that sys.exit

**Comment by jackdunger** [comment]
* just removed `sys.path.append`, currently we are asking users to install LabJackPython..
* in future this might not be required - perhaps we just need the one file

**Comment by cjones2500** [comment]
Hi,

So I did this about 3.5 years ago. I would say that having optimised code is good, but this code has reliably been tested and works.  There may be other dependencies later down the chain. I assume you've tested this with the laser switch. Its very important that the hardware is re-tested with new code.

Basically, if you have tested this with the hardware and its fine. I mean with the other lasers as well as the superK laser. But just any changes to underlying SMELLIE code need the caveat "if I fuck this up, I will destroy SNO+" so the standard "dont change it if it works" terrible physicist coding lemma sort of applied here.




On 20 Mar 2016, at 01:07, jackdunger <notifications@github.com<mailto:notifications@github.com>> wrote:


DON'T MERGE!

  *   possible edit to remove the hacked u12 file from LabJackPython, just here for @cjones2500<https://github.com/cjones2500> to look at

  *   just use the original source code from LabJackPython

  *   now explicitly call writeD = 1, as the default argument isn't the one we want
  *   the return value of eDigitalOut(...) is seemingly not used so don't worry about that
  *   add the LabJackSubmodule to the python path to avoid having to install just this file

@cjones2500<https://github.com/cjones2500>, what do you recon? I know I might be missing something, so feel free to tear this down

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/snoplus/smellie/pull/33

Commit Summary

  *   no hack laserSwitch

File Changes

  *   M software/laserSwitch.py<https://github.com/snoplus/smellie/pull/33/files#diff-0> (46)

Patch Links:

  *   https://github.com/snoplus/smellie/pull/33.patch
  *   https://github.com/snoplus/smellie/pull/33.diff

**Comment by cjones2500** [comment]
Hi @jackdunger, @jlidgard   I'm not sure about the writeD line comment? I think we want the IO lines over the D lines. I think that is the way the hardware is configured. Thus you might want writeD=0 such that it always defaults to the IO lines (if that is true, it might be worth checking this with the actual hardware). https://labjack.com/support/datasheets/u12/hardware-description/io0-io3 (is a description of the IO lines) and https://labjack.com/support/datasheets/u12/hardware-description/d0-d15 (is a description of the D lines). This might simply be a case that the LabJack is literally wired up to the IO lines inside the laser switch (Rick the technician at Oxford did this). It would be worth checking (with lasers in safe states if the writeD=1 works). My understanding is that you can write on the IO or Digital lines but the IO lines are actually connected and the default control. Also the logical digital line doesn't connect to a laser switch channel (that might not be obvious). That function increments or decrements the number, it isn't a situation of setting D5 line active in order to use laser 5, it is literally a quite pulse from the labJack that increments/or decrements the channel number. Does that clarify the situation?

**Comment by jackdunger** [comment]
Hi Chris, you're definitely right that there is a risk of breaking working code and it's easy to do more damage than good.

However, this isn't about optimisation - speed is no concern here at all. The issue is that SNODROP has many slightly different copies of the same files scattered all over the computer, and in this case a couple of hacked versions of LabJackSoftware. We're trying to make it less opaque, to avoid a complete rewrite down the line.

That is also unacceptably dangerous - if the machine goes down in 5 years, there will be no choice but to duplicate loads of files without knowing which of them work or are even being used, and hacking LabJackPython halfway through a 3000 line file..

**Comment by jackdunger** [comment]
On this bit specifically, I'm not sure I've got it yet. What we were confused about is:
* There are two hacked versions of u12.py from labjackpython

* They have been altered to: change the default value of writeD, change the return type of two functions, added a random sys.exit()

* These two files are installed, instead of being included in the software. We only knew they existed somewhere because its used.

This mess seems to come with no benifit: 
* The function is only called a few times, and we can just specify writeD = 1, or if you prefer just wrap it to change the default value
* The return values are not used at all
* the sys.exit() is probably left over from someone debugging

**Comment by jackdunger** [comment]
I completely agree that any changes require testing on hardware, that is the only option.
However, it is important that this code base is cleaned up. And we're going to need your help doing that! This PR is just here to try and jog your memory on what happened with these files.

The dev/ branch will be for things like this,  master will have no untested logic changes.
Cheers, J

**Comment by jackdunger** [comment]
To clarify:
The current SNODROP code is calling writeD=1, even though the manufacturers default is writeD = 0...

**Comment by cjones2500** [comment]
If you dont specify doesnt it default to  0. Also look at the orca_connectionv2.py anything that is linked (in any degree of separation) to that is required.




On 20 Mar 2016, at 14:32, jackdunger <notifications@github.com<mailto:notifications@github.com>> wrote:


To clarify:
The current SNODROP code is calling writeD=1, even though the manufacturers default is writeD = 0...

**Comment by jackdunger** [comment]
In the original LabJackSoftware it did. In the hacked one on snodrop it doesn't.
This is my concern - there is one person that knows this bit of code, and has forgotten. It's not on version control, and can only be found along with a couple of similar looking files by searching all of the SNODROP computer.

**Comment by jackdunger** [comment]
https://github.com/snoplus/smellie/blob/5cc02e991f29da38d70a72d056b3e5a720ecbe9c/software/RelaySwitch/build/lib/u12SMELLIE.py#L2066

**Pull request closed without merging**
